### ISSUE TITLE
Restructure repo for multiple services?

### ISSUE THREAD

**Issue by jamiejackson** [ICFI/eagle#19]
This repo is centered around the eagle (React/Java) app. We may want to restructure in anticipation of other components. For example:

* README.md
  * pipeline
    * terraform
       * ...
    * ...
  * services
    * eagle
      * README.md
      * Jenkinsfile
      * gradlew
      * ...
    * e2e_test
      * README.md
      * Jenkinsfile
      * ...
    * microservice_2
      * Jenkinsfile
      * ...

Another option would be to have a separate repo per, but that might be harder to manage in a challenge.

**Comment by jwilcoxen45** [comment]
As a group, we are going to move toward a categorized approach for the directory structure.  Each directory should align to various grading categories outlined in the government solicitation.  This will help in providing one deliverable with all relevant info to the reviewers.

Directory Structure:
-application
-design
-infrastructure
-testing_reports
                --unit_test
                --functional
                --accessibility
                --security
                --code_quality
README.md -- main documentation readme to point to individual readmes in each subdirectory.  It will have an overview of the project along with instructions on how to use each subdirectory and run the app.
