### ISSUE TITLE
Publish Sonarqube Analysis Results

### ISSUE THREAD

**Issue by jamiejackson** [ICFI/eagle#31]
@jwilcoxen45 , are the Sonarqube tests integrated? (I see some references in `build.gradle`, but not sure if it's hooked up yet.)

**Comment by jwilcoxen45** [comment]
They are set to run locally.  I plan to keep it that way too.  Run the scan locally then commit the report within the repo when we are done with the challenge.  I think it is not needed within the pipeline for the challenge.

**Comment by jwilcoxen45** [comment]
Sonarqube requires its own instance with a db to publish within a pipeline.

**Comment by jamiejackson** [comment]
Gotcha. Sounds similar to Clair's requirements.

**Comment by jwilcoxen45** [comment]
Yup, suggest just running locally, unless it is a small lift to put Clair in pipeline.
