### ISSUE TITLE
Add Jacoco Jenkins plugin to Terraform Scripts

### ISSUE THREAD

**Issue by jamiejackson** [ICFI/eagle#40]

**Comment by jwilcoxen45** [comment]
Is this needed?  Jacoco report can run locally then I can save the report within the repo during the challenge.  Within the script, seems like nice icing on the cake.

**Comment by jamiejackson** [comment]
@jwilcoxen45 The hard part's done (pulling the test results out of the build-stage of the image build and posting the results), there's only one small thing remaining: I installed the jacoco plugin manually inside of this Jenkins instance. In order for the plugin to be available in the fresh environment (without manual intervention), I just need to add the plugin reference in this line: https://github.com/ICFI/eagle/blob/38621079ef5292e9003fc36f793ff02c5984e95f/pipeline/terraform/modules/ecs-cluster/user_data.sh#L95

Did you notice the coverage results in Jenkins?

![image](https://user-images.githubusercontent.com/479475/43736049-5bb34688-998a-11e8-80ec-5077be665281.png)

**Comment by jwilcoxen45** [comment]
Yup, I will beef up the coverage over the next few days.  It is tripping on some POJOs with low coverage.

**Comment by jamiejackson** [comment]
Fixed in #48
